version: '3.3'
services:
  nginx:
    build: ./nginx
    container_name: proxy
    image: tsobu-nginx:latest
    restart: always
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    ports:
      - 80:80
      - 443:443